//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieGuide.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieGuide.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &amp; Adventure.
        /// </summary>
        public static string Action_Adventure {
            get {
                return ResourceManager.GetString("Action_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Genres.
        /// </summary>
        public static string AllGenres {
            get {
                return ResourceManager.GetString("AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        public static string Aquarius {
            get {
                return ResourceManager.GetString("Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        public static string Aries {
            get {
                return ResourceManager.GetString("Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdrops.
        /// </summary>
        public static string Backdrops {
            get {
                return ResourceManager.GetString("Backdrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorn.
        /// </summary>
        public static string Capricorn {
            get {
                return ResourceManager.GetString("Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew.
        /// </summary>
        public static string Crew {
            get {
                return ResourceManager.GetString("Crew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string Crime {
            get {
                return ResourceManager.GetString("Crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathday.
        /// </summary>
        public static string Deathday {
            get {
                return ResourceManager.GetString("Deathday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string Documentary {
            get {
                return ResourceManager.GetString("Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string Drama {
            get {
                return ResourceManager.GetString("Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        public static string Fantasy {
            get {
                return ResourceManager.GetString("Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date.
        /// </summary>
        public static string FirstAirDate {
            get {
                return ResourceManager.GetString("FirstAirDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string FirstAirDateAsc {
            get {
                return ResourceManager.GetString("FirstAirDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string FirstAirDateDesc {
            get {
                return ResourceManager.GetString("FirstAirDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Movie.
        /// </summary>
        public static string FirstMovie {
            get {
                return ResourceManager.GetString("FirstMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        public static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Stars.
        /// </summary>
        public static string GuestStars {
            get {
                return ResourceManager.GetString("GuestStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Horror {
            get {
                return ResourceManager.GetString("Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Top 250.
        /// </summary>
        public static string ImdbTop250 {
            get {
                return ResourceManager.GetString("ImdbTop250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Production.
        /// </summary>
        public static string In_Production {
            get {
                return ResourceManager.GetString("In Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job - Role.
        /// </summary>
        public static string JobRole {
            get {
                return ResourceManager.GetString("JobRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known For.
        /// </summary>
        public static string KnownFor {
            get {
                return ResourceManager.GetString("KnownFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Movie.
        /// </summary>
        public static string LastMovie {
            get {
                return ResourceManager.GetString("LastMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string Leo {
            get {
                return ResourceManager.GetString("Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        public static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Runtime.
        /// </summary>
        public static string MinimumRuntime {
            get {
                return ResourceManager.GetString("MinimumRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Votes.
        /// </summary>
        public static string MinimumVotes {
            get {
                return ResourceManager.GetString("MinimumVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Count.
        /// </summary>
        public static string MovieCount {
            get {
                return ResourceManager.GetString("MovieCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Genres.
        /// </summary>
        public static string MovieGenres {
            get {
                return ResourceManager.GetString("MovieGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        public static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        public static string Novel {
            get {
                return ResourceManager.GetString("Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        public static string OriginalLanguage {
            get {
                return ResourceManager.GetString("OriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        public static string OriginalTitle {
            get {
                return ResourceManager.GetString("OriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscar Winners.
        /// </summary>
        public static string OscarWinners {
            get {
                return ResourceManager.GetString("OscarWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Of.
        /// </summary>
        public static string PartOf {
            get {
                return ResourceManager.GetString("PartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        public static string Pisces {
            get {
                return ResourceManager.GetString("Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string PopularityaAsc {
            get {
                return ResourceManager.GetString("PopularityaAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string PopularityDesc {
            get {
                return ResourceManager.GetString("PopularityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular People.
        /// </summary>
        public static string PopularPeople {
            get {
                return ResourceManager.GetString("PopularPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Production.
        /// </summary>
        public static string Post_Production {
            get {
                return ResourceManager.GetString("Post Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posters.
        /// </summary>
        public static string Posters {
            get {
                return ResourceManager.GetString("Posters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Companies.
        /// </summary>
        public static string ProductionCompanies {
            get {
                return ResourceManager.GetString("ProductionCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Countries.
        /// </summary>
        public static string ProductionCountries {
            get {
                return ResourceManager.GetString("ProductionCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality.
        /// </summary>
        public static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string ReleaseDateAsc {
            get {
                return ResourceManager.GetString("ReleaseDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string ReleaseDateDesc {
            get {
                return ResourceManager.GetString("ReleaseDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Year.
        /// </summary>
        public static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Series.
        /// </summary>
        public static string Returning_Series {
            get {
                return ResourceManager.GetString("Returning Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string RevenueAsc {
            get {
                return ResourceManager.GetString("RevenueAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string RevenueDesc {
            get {
                return ResourceManager.GetString("RevenueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string Romance {
            get {
                return ResourceManager.GetString("Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumored.
        /// </summary>
        public static string Rumored {
            get {
                return ResourceManager.GetString("Rumored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        public static string Sagittarius {
            get {
                return ResourceManager.GetString("Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi &amp; Fantasy.
        /// </summary>
        public static string Sci_Fi_Fantasy {
            get {
                return ResourceManager.GetString("Sci_Fi_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        public static string Science_Fiction {
            get {
                return ResourceManager.GetString("Science_Fiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpio.
        /// </summary>
        public static string Scorpio {
            get {
                return ResourceManager.GetString("Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenplay.
        /// </summary>
        public static string Screenplay {
            get {
                return ResourceManager.GetString("Screenplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenstory.
        /// </summary>
        public static string Screenstory {
            get {
                return ResourceManager.GetString("Screenstory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Episodes.
        /// </summary>
        public static string SeasonEpisodes {
            get {
                return ResourceManager.GetString("SeasonEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap.
        /// </summary>
        public static string Soap {
            get {
                return ResourceManager.GetString("Soap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starring.
        /// </summary>
        public static string Starring {
            get {
                return ResourceManager.GetString("Starring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        public static string Taurus {
            get {
                return ResourceManager.GetString("Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string Thriller {
            get {
                return ResourceManager.GetString("Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Movie.
        /// </summary>
        public static string TV_Movie {
            get {
                return ResourceManager.GetString("TV_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Show Genres.
        /// </summary>
        public static string TvShowGenres {
            get {
                return ResourceManager.GetString("TvShowGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string TvShows {
            get {
                return ResourceManager.GetString("TvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        public static string Virgo {
            get {
                return ResourceManager.GetString("Virgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Average.
        /// </summary>
        public static string VoteAverage {
            get {
                return ResourceManager.GetString("VoteAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Average &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string VoteAverageAsc {
            get {
                return ResourceManager.GetString("VoteAverageAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Average &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string VoteAverageDesc {
            get {
                return ResourceManager.GetString("VoteAverageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Count &lt;b&gt;&amp;#x2B61;&lt;/b&gt;.
        /// </summary>
        public static string VoteCountAsc {
            get {
                return ResourceManager.GetString("VoteCountAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Count &lt;b&gt;&amp;#x2B63;&lt;/b&gt;.
        /// </summary>
        public static string VoteCountDesc {
            get {
                return ResourceManager.GetString("VoteCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        public static string War {
            get {
                return ResourceManager.GetString("War", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War &amp; Politics.
        /// </summary>
        public static string War_Politics {
            get {
                return ResourceManager.GetString("War_Politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        public static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
    }
}
